services:
  # TimescaleDB/PostgreSQL database
  timescale:
    image: timescale/timescaledb-ha:pg16.2-ts2.14.2-all
    restart: unless-stopped
    environment:
      TIMESCALEDB_TELEMETRY: off
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: postgres
    volumes:
      - ./db/timescale:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - timescale_network
      
networks:
  # The network the above containers share, for accessing the database
  timescale_network: